title: Avonlea at Smith Lake Florida
description: "News, documents, and updates for Avonlea homeowners."
author: 
  name: Avonlea Community
repository: avonlea-fl/avonlea-fl.github.io

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default

