title: Avonlea at Smith Lake Florida
description: "News, documents, and updates for Avonlea homeowners."
url: "https://avonlea-fl.github.io"
baseurl: ""
author: 
  name: Avonlea Community
repository: avonlea-fl/avonlea-fl.github.io

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: air

